# Generated by Django 4.1.7 on 2023-04-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
